"""add upload_message and message_is_public to media_files

Revision ID: 6e51bae1b462
Revises: 
Create Date: 2026-04-14 13:53:48.303615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e51bae1b462'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('upload_message', sa.Text(), nullable=True))
    op.add_column('media_files', sa.Column('message_is_public', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_files', 'message_is_public')
    op.drop_column('media_files', 'upload_message')
    # ### end Alembic commands ###
